FEATURE: Generate ALT text and access image properties with AssetUrl in SidekickClientEval
NEOSidekick/NEOSidekick.AiAssistant pull request #7
Opened 2023-09-13 13:14 UTC by gradinarufelix

Das kann nur auf einer öffentlichen Instanz getestet werden, weil lokale URLs natürlich nicht von der AI ausgewertet werden können. 

```yaml
properties:
  heroImageAltText:
    ui:
      inspector:
        editor: 'NEOSidekick.AiAssistant/Inspector/Editors/MagicTextAreaEditor'
        editorOptions:
          module: 'alt_tag_generator'
          arguments:
            url: 'SidekickClientEval:AssetUrl(node.properties.heroImage)'
```

2023-09-13 13:27 UTC, rolandschuetz commented on Resources/Private/NeosUserInterface/src/ContentService.ts
> +                    console.warn('An error occurred while trying to evaluate "' + value + '"\n', e);
Vermutlich wollen wir hier auch die Exception werfen.

2023-09-13 16:36 UTC, rolandschuetz commented
Wenn ich den Branch nutze um den alt_Tag_generator zu testen, dann schickt er mit immer den ganzen String `url: 'SidekickClientEval: AssetUri(node.properties.image)'` an den Server

2023-09-13 16:47 UTC, rolandschuetz requested changes
Wenn ich den Branch nutze um den alt_Tag_generator zu testen, dann schickt er mit immer den ganzen String `url: 'SidekickClientEval: AssetUri(node.properties.image)'` an den Server.

Und wenn ein Fehler vom Server zurückkommt, dann bitte als Teil des Alerts mit ausgeben.

Node onCreation streaming funktioniert in dieser Version nicht mehr.

2023-09-14 09:39 UTC, krsriq approved these changes
AI Validation liked the pull request!

2023-09-14 09:39 UTC, gradinarufelix commented
Ist behoben!

2023-09-19 09:10 UTC, rolandschuetz commented
Bei der TextArea sind Feld und Button eindeutig unterscheidbar:
![Bildschirmfoto 2023-09-19 um 11 06 51](https://github.com/NEOSidekick/NEOSidekick.AiAssistant/assets/735982/3d3906c6-e079-4011-adcc-786a2cee1a3e)


Beim TextField nicht:
![Bildschirmfoto 2023-09-19 um 11 08 22](https://github.com/NEOSidekick/NEOSidekick.AiAssistant/assets/735982/3995bf62-c542-4880-8e4d-e5f29323bd54)

Kannst du bei dem Button ein margin-top: 4px hinzufügen.

2023-09-19 10:39 UTC, merged